### ISSUE TITLE
Regarding this counting method

### ISSUE THREAD

**Issue by tang-ziwei** [14790897/GPT4-Requests-Counter#4]
Why not choose to dynamically calculate the number of messages within 3 hours? How to define the first message as the starting point? In fact, I think there is a high possibility of over 40 messages being counted within 3 hours. For example, sending 39 messages in the last ten minutes of the first three hours and sending 40 messages in the first ten minutes of the second three hours is clearly not allowed.
Therefore, it may be necessary to determine how many messages were sent within the previous 3 hours based on the timestamp of each message.

**Comment by 14790897** [comment]
I know there's a problem with my timing method, but I don't know why, can you be more specific, I still don't get it.

**Comment by 14790897** [comment]
You mean start counting from the last message forward to see if it's the full 40?

**Comment by 14790897** [comment]
I'will try this mehod, thanks

**Comment by tang-ziwei** [comment]
Basically, each message needs to be checked to see if it has reached 40 messages within the first 3 hours to determine if it can continue to be sent. I think this is similar to a sliding window, where the number of messages in any 3-hour period does not exceed 40.
If you want to quantify the representation, you can calculate the number of messages in the first three hours, which can roughly estimate how many messages can be sent later (because each message will be updated later, which may be more accurate).

**Comment by 14790897** [comment]
Found a new rule: if the cap is reached, the number of old conversations is reset to 0 
But I think there's more to the rule than that, so I'm going to drop this piece for now and just make a stats plugin.

**Comment by tang-ziwei** [comment]
Perhaps you are right, thank you.
