### ISSUE TITLE
Idea for improwing!

### ISSUE THREAD

**Issue by Depech101** [14790897/GPT4-Requests-Counter#53]
Hi there! tnx for your brilliant work!
I would like to suggest an improvement for the Chrome extension, which currently tracks the number of ChatGPT requests made during the 3-hour restrictive period and shows how much time is left before it ends. My idea is to add a function that will measure the time between queries. This will allow users to distribute their requests evenly, for example by sending them every 5 minutes, so as not to exhaust the limit too quickly and avoid situations where requests suddenly end. This will add usability, allowing more efficient planning with expansion.

**Comment by 14790897** [comment]
Users can estimate how many requests  are left and how to distribute their requests evenly by the number of questions asked in the current time period, which should be enough

**Comment by Depech101** [comment]
Okay, so I need to calculate the time with my calculator instead of just watch it in Your extention? Wery useful!

**Comment by 14790897** [comment]
The proper way to use this is to ask questions whenever necessary, without worrying about the remaining number of queries. Therefore, this feature doesn't hold much value for me. However, you're welcome to continue trying to convince me.

**Comment by Depech101** [comment]
You are welcome too. Thx.
